POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
        "name": "Jenny Rosen",
        "password": "123456",
        "email": "jennyrosen@example.com",
        "street": "Stockholmsvägen 48",
        "postcode": "54231",
        "city": "Mariestad",
        "country": "Sweden"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
        "email": "jennyrosen@example.com",
        "password": "123456"
}

###
POST http://localhost:3000/api/auth/logout


###
GET http://localhost:3000/api/auth/status